site_name: Wellken Technical Documentation
theme:
  name: material

nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting-started.md
  - Reference:
      - Python API: reference/python_api.md
      - Frontend Components: reference/frontend.md
  - Architecture: explanations/architecture.md
