from sqlalchemy import create_engine, MetaData, inspect

# 1. Setup the connection (Replace with your actual DB URL)
DATABASE_URL = "sqlite:///wellken.db" # Or your postgres URL
engine = create_engine(DATABASE_URL)

# 2. Initialize MetaData and reflect the existing database
metadata = MetaData()
metadata.reflect(bind=engine)

# Now 'metadata' is defined and populated with your tables
output_path = "docs/schema_summary.md"

with open(output_path, "w") as f:
    f.write("# Database Schema\n\n")
    # ... rest of your loop ...
    for table in metadata.tables.values():
        f.write(f"## Table: {table.name}\n")
        # ...
output_path = "docs/schema_summary.md"

# Generate the Markdown content
with open(output_path, "w") as f:
    f.write("# Database Schema\n\n")
    f.write("This page is auto-generated by the `sync-db` process.\n\n")
    # Loop through your tables and write them to the file
    for table in metadata.tables.values():
        f.write(f"## Table: {table.name}\n")
        f.write("| Column | Type |\n| --- | --- |\n")
        for column in table.columns:
            f.write(f"| {column.name} | {column.type} |\n")
        f.write("\n")

print(f"Schema documentation updated at {output_path}")
